import { Source } from '@repo/contracts';
import { Tag } from '@repo/schema';

const GENRES_FORMAT: Tag[] = [
  { slug: 'artbook', name: 'Artbook', nsfw: false },
  { slug: 'cartoon', name: 'Cartoon', nsfw: false },
  { slug: 'comic', name: 'Comic', nsfw: false },
  { slug: 'doujinshi', name: 'Doujinshi', nsfw: false },
  { slug: 'imageset', name: 'Imageset', nsfw: false },
  { slug: 'manga', name: 'Manga', nsfw: false },
  { slug: 'manhua', name: 'Manhua', nsfw: false },
  { slug: 'manhwa', name: 'Manhwa', nsfw: false },
  { slug: 'webtoon', name: 'Webtoon', nsfw: false },
  { slug: 'western', name: 'Western', nsfw: false },
  { slug: 'oneshot', name: 'Oneshot', nsfw: false },
  { slug: '_4_koma', name: '4-Koma', nsfw: false },
  { slug: 'ai_art', name: 'Art-by-AI', nsfw: false },
  { slug: 'ai_story', name: 'Story-by-AI', nsfw: false },
];

const GENRES_DEMOGRAPHIC: Tag[] = [
  { slug: 'shoujo', name: 'Shoujo(G)', nsfw: false },
  { slug: 'shounen', name: 'Shounen(B)', nsfw: false },
  { slug: 'josei', name: 'Josei(W)', nsfw: false },
  { slug: 'seinen', name: 'Seinen(M)', nsfw: false },
  { slug: 'yuri', name: 'Yuri(GL)', nsfw: false },
  { slug: 'yaoi', name: 'Yaoi(BL)', nsfw: false },
  { slug: 'futa', name: 'Futa(⚤)', nsfw: false },
  { slug: 'bara', name: 'Bara(ML)', nsfw: false },
  { slug: 'kodomo', name: 'Kodomo(Kid)', nsfw: false },
  { slug: 'old_people', name: 'Silver & Golden', nsfw: false },
  { slug: 'shoujo_ai', name: 'Shoujo ai', nsfw: false },
  { slug: 'shounen_ai', name: 'Shounen ai', nsfw: false },
  { slug: 'non_human', name: 'Non-human', nsfw: false },
];

const GENRES_NSFW: Tag[] = [
  { slug: 'gore', name: 'Gore', nsfw: true },
  { slug: 'bloody', name: 'Bloody', nsfw: true },
  { slug: 'violence', name: 'Violence', nsfw: true },
  { slug: 'ecchi', name: 'Ecchi', nsfw: true },
  { slug: 'adult', name: 'Adult', nsfw: true },
  { slug: 'mature', name: 'Mature', nsfw: true },
  { slug: 'smut', name: 'Smut', nsfw: true },
];

const GENRES_TAGS: Tag[] = [
  { slug: 'action', name: 'Action', nsfw: false },
  { slug: 'adaptation', name: 'Adaptation', nsfw: false },
  { slug: 'adventure', name: 'Adventure', nsfw: false },
  { slug: 'age_gap', name: 'Age Gap', nsfw: false },
  { slug: 'aliens', name: 'Aliens', nsfw: false },
  { slug: 'animals', name: 'Animals', nsfw: false },
  { slug: 'anthology', name: 'Anthology', nsfw: false },
  { slug: 'beasts', name: 'Beasts', nsfw: false },
  { slug: 'bodyswap', name: 'Bodyswap', nsfw: false },
  { slug: 'blackmail', name: 'Blackmail', nsfw: false },
  { slug: 'brocon_siscon', name: 'Brocon/Siscon', nsfw: false },
  { slug: 'cars', name: 'Cars', nsfw: false },
  { slug: 'cheating_infidelity', name: 'Cheating/Infidelity', nsfw: false },
  { slug: 'childhood_friends', name: 'Childhood Friends', nsfw: false },
  { slug: 'college_life', name: 'College life', nsfw: false },
  { slug: 'comedy', name: 'Comedy', nsfw: false },
  { slug: 'contest_winning', name: 'Contest winning', nsfw: false },
  { slug: 'cooking', name: 'Cooking', nsfw: false },
  { slug: 'crime', name: 'Crime', nsfw: false },
  { slug: 'crossdressing', name: 'Crossdressing', nsfw: false },
  { slug: 'cultivation', name: 'Cultivation', nsfw: false },
  { slug: 'death_game', name: 'Death Game', nsfw: false },
  { slug: 'degeneratemc', name: 'DegenerateMC', nsfw: false },
  { slug: 'delinquents', name: 'Delinquents', nsfw: false },
  { slug: 'dementia', name: 'Dementia', nsfw: false },
  { slug: 'demons', name: 'Demons', nsfw: false },
  { slug: 'drama', name: 'Drama', nsfw: false },
  { slug: 'fantasy', name: 'Fantasy', nsfw: false },
  { slug: 'fan_colored', name: 'Fan-Colored', nsfw: false },
  { slug: 'female_protagonists', name: 'Female Protagonists', nsfw: false },
  { slug: 'fetish', name: 'Fetish', nsfw: false },
  { slug: 'full_color', name: 'Full Color', nsfw: false },
  { slug: 'game', name: 'Game', nsfw: false },
  { slug: 'gender_bender', name: 'Gender Bender', nsfw: false },
  { slug: 'genderswap', name: 'Genderswap', nsfw: false },
  { slug: 'ghosts', name: 'Ghosts', nsfw: false },
  { slug: 'gyaru', name: 'Gyaru', nsfw: false },
  { slug: 'harem', name: 'Harem', nsfw: false },
  { slug: 'harlequin', name: 'Harlequin', nsfw: false },
  { slug: 'historical', name: 'Historical', nsfw: false },
  { slug: 'horror', name: 'Horror', nsfw: false },
  { slug: 'incest', name: 'Incest', nsfw: false },
  { slug: 'isekai', name: 'Isekai', nsfw: false },
  { slug: 'kids', name: 'Kids', nsfw: false },
  { slug: 'loli', name: 'Loli', nsfw: false },
  { slug: 'magic', name: 'Magic', nsfw: false },
  { slug: 'magical_girls', name: 'Magical Girls', nsfw: false },
  { slug: 'male_protagonists', name: 'Male Protagonists', nsfw: false },
  { slug: 'martial_arts', name: 'Martial Arts', nsfw: false },
  { slug: 'master_servant', name: 'Master-Servant', nsfw: false },
  { slug: 'mecha', name: 'Mecha', nsfw: false },
  { slug: 'medical', name: 'Medical', nsfw: false },
  { slug: 'military', name: 'Military', nsfw: false },
  { slug: 'monster_girls', name: 'Monster Girls', nsfw: false },
  { slug: 'monsters', name: 'Monsters', nsfw: false },
  { slug: 'music', name: 'Music', nsfw: false },
  { slug: 'mystery', name: 'Mystery', nsfw: false },
  { slug: 'netori', name: 'Netori', nsfw: false },
  { slug: 'netorare', name: 'Netorare/NTR', nsfw: false },
  { slug: 'ninja', name: 'Ninja', nsfw: false },
  { slug: 'office_workers', name: 'Office Workers', nsfw: false },
  { slug: 'omegaverse', name: 'Omegaverse', nsfw: false },
  { slug: 'parody', name: 'Parody', nsfw: false },
  { slug: 'philosophical', name: 'Philosophical', nsfw: false },
  { slug: 'police', name: 'Police', nsfw: false },
  { slug: 'post_apocalyptic', name: 'Post-Apocalyptic', nsfw: false },
  { slug: 'psychological', name: 'Psychological', nsfw: false },
  { slug: 'reincarnation', name: 'Reincarnation', nsfw: false },
  { slug: 'revenge', name: 'Revenge', nsfw: false },
  { slug: 'reverse_harem', name: 'Reverse Harem', nsfw: false },
  { slug: 'romance', name: 'Romance', nsfw: false },
  { slug: 'samurai', name: 'Samurai', nsfw: false },
  { slug: 'school_life', name: 'School Life', nsfw: false },
  { slug: 'sci_fi', name: 'Sci-Fi', nsfw: false },
  { slug: 'shota', name: 'Shota', nsfw: false },
  { slug: 'showbiz', name: 'Showbiz', nsfw: false },
  { slug: 'slice_of_life', name: 'Slice of Life', nsfw: false },
  { slug: 'sm_bdsm', name: 'SM/BDSM', nsfw: false },
  { slug: 'space', name: 'Space', nsfw: false },
  { slug: 'sports', name: 'Sports', nsfw: false },
  { slug: 'spy', name: 'Spy', nsfw: false },
  { slug: 'step_family', name: 'Step Family', nsfw: false },
  { slug: 'super_power', name: 'Super Power', nsfw: false },
  { slug: 'superhero', name: 'Superhero', nsfw: false },
  { slug: 'supernatural', name: 'Supernatural', nsfw: false },
  { slug: 'survival', name: 'Survival', nsfw: false },
  { slug: 'teacher_student', name: 'Teacher-Student', nsfw: false },
  { slug: 'thriller', name: 'Thriller', nsfw: false },
  { slug: 'time_travel', name: 'Time Travel', nsfw: false },
  { slug: 'traditional_games', name: 'Traditional Games', nsfw: false },
  { slug: 'tragedy', name: 'Tragedy', nsfw: false },
  { slug: 'vampires', name: 'Vampires', nsfw: false },
  { slug: 'video_games', name: 'Video Games', nsfw: false },
  { slug: 'villainess', name: 'Villainess', nsfw: false },
  { slug: 'virtual_reality', name: 'Virtual Reality', nsfw: false },
  { slug: 'wuxia', name: 'Wuxia', nsfw: false },
  { slug: 'xianxia', name: 'Xianxia', nsfw: false },
  { slug: 'xuanhuan', name: 'Xuanhuan', nsfw: false },
  { slug: 'zombies', name: 'Zombies', nsfw: false },
];

export const config: Source = {
  name: 'MangaPark',
  slug: 'mangapark',
  url: 'https://mangapark.org',
  referer: 'https://mangapark.org',
  icon: 'https://raw.githubusercontent.com/angelocarasig/alethia/refs/heads/main/sources/mangapark/public/icon.png',
  languages: ['en'],
  auth: {
    type: 'cookie',
    required: true,
    fields: ['cookie'],
  },
  nsfw: false,
  search: {
    sort: [
      'rating',
      'popularity',
      'chapters',
      'updatedAt',
      'createdAt',
      'title',
    ],
    filters: [
      'includeTag',
      'excludeTag',
      'status',
      'originalLanguage',
      'minChapters',
    ],
    tags: [
      ...GENRES_FORMAT,
      ...GENRES_DEMOGRAPHIC,
      ...GENRES_NSFW,
      ...GENRES_TAGS,
    ],
  },
  presets: [],
};

export const ENDPOINTS = {
  search: 'https://mangapark.org/search',
  title: (slug: string) => `https://mangapark.org/title/${slug}`,
} as const;
